### ISSUE TITLE
Unable to add more URLs

### ISSUE THREAD

**Issue by ZicPL** [domrafacz/website-monitor#6]
Your application is tested by me successfully, but I encountered one problem and I don't know what to do next:

> "You cannot add more websites"

![Screenshot](https://github.com/user-attachments/assets/4e869dff-0cb2-48c3-b32b-93124bb348a4)

The button is disabled and the above message appears. What can I do to add more pages?

**Comment by domrafacz** [comment]
You can change the limit using admin panel. You have to create user with admin rights, then you can access admin panel from the menu in upper right corner.

**Comment by ZicPL** [comment]
@domrafacz Thanks for Your answer. I don't have such an option in Settings:
![where](https://github.com/user-attachments/assets/eecde790-3d9e-409f-9102-72d8344e6f32)
(I added websites as a administrator. Does it matter? Should I add websites as a user?

**Comment by domrafacz** [comment]
In users, when you click on the user email, you will open the user edit form

**Comment by ZicPL** [comment]
That's right. I don't know why, but I was in this tab before and didn't pay attention properly. Thanks for Your help and I'll keep testing ;)
